# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zskoo_Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_record', models.TextField(default='null')),
                ('conformity', models.CharField(max_length=100)),
                ('resume', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Zskoo_Ctrl_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrl_point', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zskoo_Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_object', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zskoo_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrl_object', models.TextField(default='null')),
                ('industry', models.CharField(max_length=100)),
                ('S', models.CharField(max_length=20)),
                ('A', models.CharField(max_length=20)),
                ('G', models.CharField(max_length=20)),
            ],
        ),
    ]
