# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zskoo_conclusion',
            name='main_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Main'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zskoo_main',
            name='ctrl_point_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Ctrl_Point'),
        ),
        migrations.AddField(
            model_name='zskoo_main',
            name='zskoo_kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Kind'),
        ),
    ]
