# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_zskoo_conclusion_zskoo_ctrl_point_zskoo_kind_zskoo_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zskoo_main',
            name='condusion_id',
        ),
        migrations.AddField(
            model_name='zskoo_conclusion',
            name='main_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Main'),
        ),
        migrations.AlterField(
            model_name='zskoo_conclusion',
            name='conformity',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='zskoo_ctrl_point',
            name='ctrl_point',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='zskoo_kind',
            name='security_object',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='zskoo_main',
            name='industry',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
