# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_auto_20170703_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='zskoo_conclusion',
            name='ctrl_point_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Ctrl_Point'),
        ),
        migrations.AddField(
            model_name='zskoo_conclusion',
            name='zskoo_kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Kind'),
        ),
    ]
