# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_auto_20170716_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuheqk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conformity', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
