# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_auto_20170701_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zskoo_main',
            name='ctrl_point_id',
            field=models.ForeignKey(default='XXX', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Ctrl_Point'),
        ),
    ]
