# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-17 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0005_fuheqk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zskoo_conclusion',
            name='conformity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.fuheqk'),
        ),
    ]
