# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_auto_20170717_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='zskoo_conclusion',
            name='A',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zskoo_conclusion',
            name='G',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zskoo_conclusion',
            name='S',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zskoo_conclusion',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
