# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_auto_20170701_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zskoo_conclusion',
            name='main_id',
        ),
        migrations.AddField(
            model_name='zskoo_main',
            name='condusion_id',
            field=models.ForeignKey(default='XXX', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Conclusion'),
        ),
    ]
