# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_auto_20170701_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zskoo_main',
            name='condusion_id',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Conclusion'),
        ),
        migrations.AlterField(
            model_name='zskoo_main',
            name='ctrl_point_id',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Ctrl_Point'),
        ),
        migrations.AlterField(
            model_name='zskoo_main',
            name='zskoo_kind',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Zskoo_Kind'),
        ),
    ]
